### ISSUE TITLE
Clear button in Search component

### ISSUE THREAD

**Issue by itzmidinesh** [chingu-voyages/v45-tier1-team-01#18]
**__Task Description__**
We will implement a clear button inside the search component. The clear button should allow user to easily reset all search criteria and revert the detailed data display.

**__Functionality__**
When user clicks on "clear" button, the following should happen:
- [x] Search fields should reset.
- [x] Detail display should go back to displaying the entire entire dataset.
- [x] Summary metrics should update to reflect entire dataset.

**__Linked Issues__**
This task is part of epic #14 (Search component for filtering Meteor data)
