### ISSUE TITLE
Search button in Search component

### ISSUE THREAD

**Issue by itzmidinesh** [chingu-voyages/v45-tier1-team-01#22]
**__Task Description__**
We will implement a search button inside the search component. The search button should allow user to start searching and display the matching data display.

**__Functionality__**
When user clicks on "search" button, the following should happen:
- [x] Collect search criteria entered by user.
- [x] Search the dataset using search critirea.
- [x] Update detailed data display with matching data.
- [x] Update summary metrics based on search results.

**__Linked Issues__**
This task is part of epic #14 (Search component for filtering Meteor data)

**Comment by ashiyaman** [comment]
As discussed, we are not implementing search button as the search we have done is more fast and dynamic
