### ISSUE TITLE
Table view

### ISSUE THREAD

**Issue by CharanMN7** [chingu-voyages/v45-tier1-team-01#27]
**__Task Description__**
Create a table that would present the data of the meteorites.
- [x] The values in the table are scrollable.
- [x] Clicking on a row in the table will make a card pop-up with all the details of the respective meteorite.
- [x] The pop-up must have a close button.
